### ISSUE TITLE
Limit the width of the window or number of characters (or both?)

### ISSUE THREAD

**Issue by diachini** [jmhobbs/ShowKeys#4]
I love this tool so much. It solves a problem I've regularly tried to find a solution for (lots of pairing at work + lots of sweet VIM knowledge to share + ShowKeys = really handy way to see what that black-magic was that your pair just typed).

The one issue I've had to work around a couple times now is the fact that the window will extend itself if you type something longer than its previous width.  If you are in a very long document in VIM and you're just reading it (jumping around and whatnot) the window will expand and expand -- eventually groing to be wider than the monitor.

It'd be awesome to do one (or more) of the following:

```
 1. Stop expanding when it's as wide as the monitor
 2. Truncate the text after a certain number of characters
 3. Allow a user to lock the maximum width
 4. Right-align the text presented, and always show the most recent X characters
 5. Jump back to the "default" size whenever a long string is cleared out of it
```

I haven't dabbled with much OSX code - but if I get a chance, I'd love to help build upon this already incredible tool!

![screenshot 2015-07-01 10 51 18](https://cloud.githubusercontent.com/assets/2895888/8457415/3b2643de-1fdf-11e5-85b4-cf416a9c1ea0.png)

**Comment by jmhobbs** [comment]
Yowza!  Do you have the fade out delay cranked way up or are you just a lightning fast typer!?

Great idea though.  I think the easiest option is a "max X characters" setting.  I'm not so great with OSX either, so I'll start with the easy fix first :)

**Comment by jmhobbs** [comment]
I also added a (non-configurable) window shrink in c364702325d34bb0892b5e4b5208073ac0f0ccde

![show-keys-resize](https://cloud.githubusercontent.com/assets/115059/8460699/6f066f3c-1fec-11e5-8268-af0fed805247.gif)

**Comment by jmhobbs** [comment]
Added a build for convenience.

https://github.com/jmhobbs/ShowKeys/releases/tag/0.3

**Comment by diachini** [comment]
My fade timeout was set to Never (0.00s), so that was how everything was hanging around in there forever (is that the default for new users?).  

An addition that could be added with that auto window shrink would be for when a new command gets started, it could shrink back down (so if I have 32 "j"s in it, and I type a space, it could shrink back down to the default size.  (Thanks for the ridiculously fast fix so far though!  Love the tool even more now :-) )

**Comment by jmhobbs** [comment]
Whoops.  Fade timeout should have defaulted to 1.0s, I'll look into that.

Good idea on the auto-shrink after command.  There are some other wonky things there that need to be adjusted.

Thanks for the feature request!
