### ISSUE TITLE
Packaged App

### ISSUE THREAD

**Issue by n370** [jmhobbs/ShowKeys#7]
Where do I get it? Do I have to bundle it myself?
Can you please document the steps for beginners like me?

**Comment by jmhobbs** [comment]
I'll add a link in the reader, but you can always grab a release from here; https://github.com/jmhobbs/ShowKeys/releases

It's not signed, so you may have to tell OS X it's okay to run via the security panel in preferences.

**Comment by n370** [comment]
Thanks man, awesome project.
