### ISSUE TITLE
No key is displayed, but `--TEST--`

### ISSUE THREAD

**Issue by ryrych** [jmhobbs/ShowKeys#8]
Hi,

I did all the necessary steps. ShowKeys opens, but apart from `--TEST--` no key is recorded.

OSX 10.11.2
Let me know if you need more information.

**Comment by jmhobbs** [comment]
That's no good.  I'm on 10.11.3 but can't replicate.

Do you only see `--TEST--` during configuration with the Preferences window, or is it up constantly?

Also, make sure the ShowKeys app isn't focused, it won't display keystrokes then (which is probably it's own bug)

**Comment by ryrych** [comment]
It seems that some OSX apps stop working until you install latest system updates. Now it works perfectly and looks like a nice alternative to KeyCastr. :)

**Comment by jmhobbs** [comment]
Th and for following up!

If you have any suggestions for improvements, please feel free to file
issues for them.

On Saturday, February 6, 2016, Wojtek Ryrych notifications@github.com
wrote:

> It seems that some OSX apps stop working until you install latest system
> updates. Now it works perfectly and looks like a nice alternative to
> KeyCastr. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jmhobbs/ShowKeys/issues/8#issuecomment-180828175.

## 
- John Hobbs

john@velvetcache.org

http://www.velvetcache.org/
